name: Unit Test

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install project dependencies
        run: npm install

      - name: Run unit tests
        run: npm run test
